// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	"context"
	user "douyin/kitex_gen/video"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

var videoServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*user.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{
		"PublishAction": kitex.NewMethodInfo(publishActionHandler, newVideoServicePublishActionArgs, newVideoServicePublishActionResult, false),
		"PublishList":   kitex.NewMethodInfo(publishListHandler, newVideoServicePublishListArgs, newVideoServicePublishListResult, false),
		"Feed":          kitex.NewMethodInfo(feedHandler, newVideoServiceFeedArgs, newVideoServiceFeedResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func publishActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.VideoServicePublishActionArgs)
	realResult := result.(*user.VideoServicePublishActionResult)
	success, err := handler.(user.VideoService).PublishAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishActionArgs() interface{} {
	return user.NewVideoServicePublishActionArgs()
}

func newVideoServicePublishActionResult() interface{} {
	return user.NewVideoServicePublishActionResult()
}

func publishListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.VideoServicePublishListArgs)
	realResult := result.(*user.VideoServicePublishListResult)
	success, err := handler.(user.VideoService).PublishList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServicePublishListArgs() interface{} {
	return user.NewVideoServicePublishListArgs()
}

func newVideoServicePublishListResult() interface{} {
	return user.NewVideoServicePublishListResult()
}

func feedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.VideoServiceFeedArgs)
	realResult := result.(*user.VideoServiceFeedResult)
	success, err := handler.(user.VideoService).Feed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceFeedArgs() interface{} {
	return user.NewVideoServiceFeedArgs()
}

func newVideoServiceFeedResult() interface{} {
	return user.NewVideoServiceFeedResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PublishAction(ctx context.Context, req *user.DouyinPublishActionRequest) (r *user.DouyinPublishActionResponse, err error) {
	var _args user.VideoServicePublishActionArgs
	_args.Req = req
	var _result user.VideoServicePublishActionResult
	if err = p.c.Call(ctx, "PublishAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PublishList(ctx context.Context, req *user.DouyinPublishListRequest) (r *user.DouyinPublishListResponse, err error) {
	var _args user.VideoServicePublishListArgs
	_args.Req = req
	var _result user.VideoServicePublishListResult
	if err = p.c.Call(ctx, "PublishList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Feed(ctx context.Context, req *user.DouyinFeedRequest) (r *user.DouyinFeedResponse, err error) {
	var _args user.VideoServiceFeedArgs
	_args.Req = req
	var _result user.VideoServiceFeedResult
	if err = p.c.Call(ctx, "Feed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
